In [19]:
import numpy as np
import pandas as pd
from sound import *

df = pd.read_csv('parte_nome_sexo.csv')
df

df = df[df['PrimeiroNomeNoAccents'].notna()]
df = df[:50000]

In [20]:
df['Sounde'] = df.apply(lambda row: soundex(row['PrimeiroNomeNoAccents']), axis=1)

In [21]:
df[df['Masculino'] == df['Feminino']]

Empty DataFrame
Columns: [Masculino, Feminino, PrimeiroNomeNoAccents, Sounde]
Index: []

In [22]:
df['SoundexIndice0'] = df[df['Sounde'].notna()].apply(lambda row: ord(row['Sounde'][0:1]), axis=1)
df['SoundexIndice1'] = df[df['Sounde'].notna()].apply(lambda row: int(row['Sounde'][1:2]), axis=1)
df['SoundexIndice2'] = df[df['Sounde'].notna()].apply(lambda row: int(row['Sounde'][2:3]), axis=1)
df['SoundexIndice3'] = df[df['Sounde'].notna()].apply(lambda row: int(row['Sounde'][3:4]), axis=1)

In [23]:
df['Leng'] = df.apply(lambda row: len(row['PrimeiroNomeNoAccents']), axis=1)

In [24]:
for i in range(0, 10):
    df['LetraIndice' + str(i)] = df.apply(lambda row: getascii(row, i), axis=1)
    print('ok {0}'.format(i))

ok 0
ok 1
ok 2
ok 3
ok 4
ok 5
ok 6
ok 7
ok 8
ok 9


In [25]:
def getascii(row, indice):
    c = row['PrimeiroNomeNoAccents'][indice:indice+1]
    if(len(c) == 0):
        return np.nan
    return ord(c)

    

In [26]:
mean = df['LetraIndice1'].mean()
#df_backup = df
s = df[df['LetraIndice1'].isna()]['LetraIndice1']


values = {
    'LetraIndice1': df['LetraIndice1'].mean(), 
    'LetraIndice2': df['LetraIndice2'].mean(), 
    'LetraIndice3': df['LetraIndice3'].mean(), 
    'LetraIndice4': df['LetraIndice4'].mean(), 
    'LetraIndice5': df['LetraIndice5'].mean(), 
    'LetraIndice6': df['LetraIndice6'].mean(), 
    'LetraIndice7': df['LetraIndice7'].mean(), 
    'LetraIndice8': df['LetraIndice8'].mean(), 
    'LetraIndice9': df['LetraIndice9'].mean(), 
}

df = df.fillna(value=values)
df_Mean = pd.DataFrame(values, index=[0])
df_Mean.to_csv("mediaLetras.csv", index=False)

In [127]:
X = df.drop(['Masculino', 'Feminino', 'PrimeiroNomeNoAccents', 'Sounde'], axis=1)
#y = df.loc[:, ['Masculino', 'Feminino']]
y = df.loc[:, ['Masculino']]

X

SoundexIndice0  SoundexIndice1  SoundexIndice2  SoundexIndice3  Leng  \
0                  98               5               3               0     8   
1                 115               2               6               3    10   
2                 108               2               0               0     4   
3                 100               5               4               0     6   
4                 109               6               2               0     6   
5                  97               3               0               0     4   
6                 119               4               3               6     6   
7                 115               5               0               0     5   
8                 109               6               2               0     6   
9                 107               1               5               0     6   
10                118               4               3               6     7   
11                108               5               0               0     4   
12                108               2               0               0     4   
13                101               2               5               0     7   
14                 99               4               0               0     5   
15                105               4               5               0     4   
16                 99               6               4               2     6   
17                100               2               0               0     5   
18                110               2               4               5     9   
19                101               1               4               5     7   
20                 99               6               4               2     6   
21                111               3               5               6     6   
22                106               2               5               4     7   
23                 97               3               4               3     8   
24                 98               5               2               5     8   
25                101               3               5               4     8   
26                101               3               2               5     5   
27                 97               5               3               6     8   
28                102               4               1               0     6   
29                106               0               0               0     4   
...               ...             ...             ...             ...   ...   
49970             108               3               5               6     8   
49971             106               6               2               0     5   
49972             109               6               0               0     5   
49973             106               4               5               0     7   
49974             114               4               1               6     9   
49975             114               2               6               4     9   
49976             103               5               4               3     8   
49977             115               5               3               6     6   
49978             119               2               5               6     6   
49979             118               5               6               0     5   
49980              97               6               2               5     8   
49981             106               4               0               0     5   
49982              97               3               4               2     7   
49983             103               5               2               4     7   
49984             114               1               2               5     6   
49985             101               4               0               0     3   
49986             109               6               0               0     5   
49987              97               3               5               4     8   
49988             109               6               2    

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.33, random_state=7)

y = np.array(y)
y = np.ravel(y)

#est = RandomForestClassifier(n_estimators = 40).fit(X, y)
#est.score(X, y)

#est = reg

In [29]:
c = pd.concat([df.loc[:,'PrimeiroNomeNoAccents'], X], axis=1)

In [30]:
from __future__ import absolute_import, division, print_function

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

1.13.1


In [31]:
X.shape

(50000, 15)

In [134]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X)
scaler.scale_      

#print(df.columns.shape)

Xs = scaler.transform(X)
pd.DataFrame(Xs, columns=X.columns)
#pd.DataFrame(Xs)

SoundexIndice0  SoundexIndice1  SoundexIndice2  SoundexIndice3  \
0           -1.261391        0.729810        0.166601       -0.803505   
1            1.387955       -0.944681        1.621806        0.532908   
2            0.297048       -0.944681       -1.288603       -0.803505   
3           -0.949703        0.729810        0.651670       -0.803505   
4            0.452892        1.287974       -0.318467       -0.803505   
5           -1.417235       -0.386517       -1.288603       -0.803505   
6            2.011331        0.171647        0.166601        1.869321   
7            1.387955        0.729810       -1.288603       -0.803505   
8            0.452892        1.287974       -0.318467       -0.803505   
9            0.141204       -1.502845        1.136738       -0.803505   
10           1.855487        0.171647        0.166601        1.869321   
11           0.297048        0.729810       -1.288603       -0.803505   
12           0.297048       -0.944681       -1.288603       -0.803505   
13          -0.793859       -0.944681        1.136738       -0.803505   
14          -1.105547        0.171647       -1.288603       -0.803505   
15          -0.170484        0.171647        1.136738       -0.803505   
16          -1.105547        1.287974        0.651670        0.087437   
17          -0.949703       -0.944681       -1.288603       -0.803505   
18           0.608736       -0.944681        0.651670        1.423850   
19          -0.793859       -1.502845        0.651670        1.423850   
20          -1.105547        1.287974        0.651670        0.087437   
21           0.764579       -0.386517        1.136738        1.869321   
22          -0.014640       -0.944681        1.136738        0.978379   
23          -1.417235       -0.386517        0.651670        0.532908   
24          -1.261391        0.729810       -0.318467        1.423850   
25          -0.793859       -0.386517        1.136738        0.978379   
26          -0.793859       -0.386517       -0.318467        1.423850   
27          -1.417235        0.729810        0.166601        1.869321   
28          -0.638016        0.171647       -0.803535       -0.803505   
29          -0.014640       -2.061008       -1.288603       -0.803505   
...               ...             ...             ...             ...   
49970        0.297048       -0.386517        1.136738        1.869321   
49971       -0.014640        1.287974       -0.318467       -0.803505   
49972        0.452892        1.287974       -1.288603       -0.803505   
49973       -0.014640        0.171647        1.136738       -0.803505   
49974        1.232111        0.171647       -0.803535        1.869321   
49975        1.232111       -0.944681        1.621806        0.978379   
49976       -0.482172        0.729810        0.651670        0.532908   
49977        1.387955        0.729810        0.166601        1.869321   
49978        2.011331       -0.944681        1.136738        1.869321   
49979        1.855487        0.729810        1.621806       -0.803505   
49980       -1.417235        1.287974       -0.318467        1.423850   
49981       -0.014640        0.171647       -1.288603       -0.803505   
49982       -1.417235       -0.386517        0.651670        0.087437   
49983       -0.482172        0.729810       -0.318467        0.978379   
49984        1.232111       -1.502845       -0.318467        1.423850   
49985       -0.793859        0.171647       -1.288603       -0.803505   
49986        0.452892        1.287974       -1.288603       -0.803505   
49987       -1.417235       -0.386517        1.136738        0.978379   
49988        0.452892        1.287974       -0.318467       -0.803505   
49989        2.011331        0.171647        1.136738        0.087437   
49990        1.232111        0.729810        0.651670        0.532908   
49991        1.855487       -0.944681        0.166601        1.869321   
49992       -0.949703        0.729810        0.651670       -0.80

In [33]:
y = np.array(y)
y

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [42]:
l0 = tf.keras.layers.Dense(units=15, input_shape=[15])  

model = keras.Sequential([
    l0,
    keras.layers.Dense(100, activation=tf.nn.relu),
    keras.layers.Dense(100, activation=tf.nn.relu),
    keras.layers.Dense(100, activation=tf.nn.relu),
    keras.layers.Dense(2, activation=tf.nn.softmax)
])
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [46]:
model.fit(Xs, y, epochs=4000)

Epoch 1/4000
36960/50000 [=====================>........] - ETA: 0s - loss: 0.0859 - acc: 0.9745

KeyboardInterrupt: 

In [70]:
scaler = preprocessing.StandardScaler().fit(X_test)
Xts = scaler.transform(X_test)
#Xts


print(Xts.shape)

x1 = Xts[0]
x2 = (np.expand_dims(x1, 0))
print(x1.shape)
print(x2.shape)

(16500, 15)
(15,)
(1, 15)


In [96]:
predictions = model.predict(x2)

print(x2)
print("yt=", yt[0])

predictions


[[-1.10746613  0.17026561  0.16556582  1.42174629  1.54155213 -1.09340363
  -0.03433156 -1.21542486  0.65754621 -0.8658242  -0.57677781 -0.03011117
  -1.55887045 -1.38420422  0.00268169]]
yt= 1


array([[9.197579e-08, 9.999999e-01]], dtype=float32)

In [125]:


#test_loss, test_acc = model.evaluate(Xts, yt)

skip = 10
take = 20
test_loss, test_acc = model.evaluate(Xts[skip:take+skip], yt[skip:take+skip])
#test_loss, test_acc = model.evaluate(x2, (np.expand_dims(yt[0:10], 0)))
print('Test accuracy:', test_acc)



20/20 [==============================] - 0s 50us/sample - loss: 0.0428 - acc: 1.0000
Test accuracy: 1.0


In [63]:
predictions

array([[9.19757923e-08, 9.99999881e-01],
       [3.28690290e-01, 6.71309710e-01],
       [1.98901771e-03, 9.98011053e-01],
       ...,
       [1.40856955e-05, 9.99985933e-01],
       [1.38951894e-02, 9.86104786e-01],
       [1.00000000e+00, 7.12773549e-14]], dtype=float32)

In [98]:
yt = np.ravel(y)
yt

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)